services:
  - type: web
    name: odoo-web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    startCommand: >
      odoo --db_host=$DB_HOST --db_port=$DB_PORT
           --db_user=$DB_USER --db_password=$DB_PASSWORD
    envVars:
      - key: DB_HOST
        value: ep-long-scene-a2bjs08m-pooler.eu-central-1.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        sync: false
    disk:
      name: odoo-data
      mountPath: /var/lib/odoo
      sizeGB: 1